### ISSUE TITLE
Anybody home?

### ISSUE THREAD

**Issue by IPv6** [zwetan/as3-universal-analytics#1]
So.. is this project dead?

**Comment by zwetan** [comment]
a bit late related to the 15th september date announced, by this week-end you'll get the 1st release

**Comment by ZwickTheGreat** [comment]
Looking forward for this! Thanks for all zwetan.

**Comment by lucien144** [comment]
Any news?

**Comment by zwetan** [comment]
coming soon, all implementations/refactor done
it works for Flash, SWF, AIR, projector, command-line, server-side AS3, shell scripts, etc.

finishing code clean up, documentation and examples

**Comment by lucien144** [comment]
Awesome, cannot wait. Thanks!

**Comment by zwetan** [comment]
v0.8 is out
