### ISSUE TITLE
I can't get it working

### ISSUE THREAD

**Issue by colouredFunk** [zwetan/as3-universal-analytics#14]
I must be missing something, but I can't seem to get any data showing up in Google Analytics.

The simplest integration - 
    var tracker:AppTracker = new AppTracker( "UA-XXXXXX-1");
    tracker.screenview("HOME");

But nothing is showing up in RealTime in Google?

I've tried sending Configuration to AppTracker to  -
    var config:Configuration = new Configuration();
    config.forcePOST = true;
    var tracker:AppTracker = new AppTracker( "UA-XXXXXX-1", config);

I've also tried setting up the two classes as detailed here - https://github.com/zwetan/as3-universal-analytics/wiki/TrackingConfiguration (MyTracker and MySender) but after instantiating MyTracker (var tracker:MyTracker = new MyTracker() ), I'm not too sure how to continue with this as trackingId doesn't exactly get applied...? Has anyone got an example project template with it working? Or No where I'm going wrong?

**Comment by zwetan** [comment]
that's normal

to send screenview you need at least the "app name"
without it the hit request will be considered invalid

see the documentation about [screens](https://github.com/zwetan/as3-universal-analytics/wiki/TrackingDetailsAndTricks#screens)

for the tracking configuration, don't try to implement your own tracker right away
- reuse either WebTracker or AppTracker
- only customise the sender
  eg. `config.senderType = "libraries.uanalytics.tracker.senders.TraceHitSender";`

also even if it is possible to see a hit request right away
sometimes it can take few hours before the web property is considered "active"

if you encounter more problem try to post the full source code you had used
and if possible use the backtick so it shows as source code in the issue

**Comment by colouredFunk** [comment]
Great thanks, it's working now! :)
