### ISSUE TITLE
Google Analytics reporting different number of views than NewGrounds

### ISSUE THREAD

**Issue by diminuto** [zwetan/as3-universal-analytics#21]
Hello,
I have followed the simplest implementation of the libraries:

```
public function sendPageview( page:String, title:String = "" ):void
{       
      var trackingID:String = "UA-XXXXX";
       var config:Configuration = new Configuration(); 
       config.forcePOST = true;
       var tracker:WebTracker = new WebTracker( trackingID, config );
       tracker.pageview( page, title );
}
```

It seems like the stats are not working everytime: I uploaded my game to Newgrounds last night. According to them 110 people played the game. However, Google Analytics reckons only 48 played. Is there anything I'm missing?

Thanks!

**Comment by zwetan** [comment]
could be the [session management](https://github.com/zwetan/as3-universal-analytics/wiki/TrackingDetailsAndTricks#session-management), could be something else

others could be
- problem with the domain name, hits will come from newgrounds.com
- understanding of the tracking "played the game"  
  for some people
  - viewing it once is enough to count
  - clicking a button "play"
  - ending a level
- how newgrounds does tracking  
  eg. user refresh the page 3 times and count 3 tracking
- how GA does tracking  
  eg. user play 3 times within 30 minutes, count 1 tracking
- could be the [sampling](https://github.com/zwetan/as3-universal-analytics/wiki/TrackingDetailsAndTricks#sampling)
- etc.

my advice:
- setup a [mobile app property](https://github.com/zwetan/as3-universal-analytics/wiki/GettingStarted#properties), not a website
- it will allow you to define your game with a name, id, version, etc.
- track screens and not pages  
  `tracker.screenview( "Intro" );`  
  `tracker.screenview( "Level 1" );`  
  `tracker.screenview( "Level 2" );`
- use events for fine grained tracking  
  `tracker.event( "Game", "click", "play" );`  
  `tracker.event( "Game", "start", "level 1" );`  
  `tracker.event( "Game", "end", "level 1" );`  
  `tracker.event( "Game", "lost" );`  
  `tracker.event( "Game", "win" );`
- use timer for even more details tracking  
  `tracker.timing( "Game", "level1", 300 );`  
  `tracker.timing( "Game", "level2", 400 );`  
  `tracker.timing( "Game", "total", 1200 );`

**Comment by zwetan** [comment]
"as is" I don't see that as a bug

**Comment by diminuto** [comment]
Thanks a lot for your quick reply zwetan, I will try with your suggested approach

**Comment by zwetan** [comment]
no prob, and if you found where was the problem
please come back and make a little summary
so it could maybe help others with a similar problem
