### ISSUE TITLE
Device info

### ISSUE THREAD

**Issue by pixelthis-peter** [zwetan/as3-universal-analytics#23]
Fantastic package - I am using it in a live project and mostly everything is perfect. The only problem is that the device information is not correct.  All Android devices are 'unknown' and all Apple devices are 'iPodTouch'.  I have some other libraries for detecting device type - where can I set these details inside the tracker?

For example, I have some code which can tell me that the device is an "iPad AIR 2" - which property inside the AppTracker can I set to this value?

**Comment by zwetan** [comment]
The library itself does not detect the device, this is done on the Google Analytics backend.
The GA server when they receive a request deduce the device from the user-agent string.

The first thing you can try is to send the data with POST
see [Transport / Using POST](https://developers.google.com/analytics/devguides/collection/protocol/v1/reference#using-post)

If that still does not correct the problem, you can override the user-agent param
with [User Agent Override](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ua)

In the library you have 2 ways to do that

with the configuration

``` as3
var config:Configuration = new Configuration();
    config.forcePOST = true;
    config.overrideUserAgent = "(your custom user-agent here)";

var tracker:WebTracker = new WebTracker( "UA-12345-67", config );
```

with the tracker itself

``` as3
var tracker:WebTracker = new WebTracker( "UA-12345-67", config );
    tracker.set( Tracker.USER_AGENT_OVERRIDE, "(your custom user-agent here)" );
```

you can see a small example and some notes here
[generateCLIUserAgent.as](https://github.com/zwetan/as3-universal-analytics/blob/master/src/libraries/uanalytics/utils/generateCLIUserAgent.as)

in particular this

> Note that Google has libraries to identify real user agents.
> Hand crafting your own agent could break at any time.
> 
> a wrong user-agent could be the reason of a hit request not being
> registered by the Google Analytics Servers.

Sniffing / detecting user-agent to extrapolate the OS / device / etc. is a slippery slope
Google Analytics do that on the backend, from the library we have no control over it
even if you copy/paste a real user-agent you took from a device
but somehow GABE does not recognize it, not only it will not change the device / OS / etc.
but it will also ignore the request, eg. your tracking will not appears in the results.

If I was really forced to override the user-agent, I would try to do it in few steps
- detect the device  
  see for ex [Detecting and limiting Apple iOS devices](http://www.adobe.com/devnet/air/articles/multiple-screen-sizes.html)
- have a map of OS/Device to real user-agent strings  
- send those UA

really test hard with the GA backed that those UA are valid and accepted
