### ISSUE TITLE
Flow player Flash - Would it be possible to integrate 

### ISSUE THREAD

**Issue by grantkemp** [zwetan/as3-universal-analytics#24]
I raised an issue in Flow Player flash to try get them to jump to universal.  It looks like this library would be the ideal solution. 

Would someone be able to advise how to integrate it? I personally know GA/ MPreally well, but flash is not my strong point.

**Comment by zwetan** [comment]
I'll post something on the flow player issue you raised
https://github.com/flowplayer/flash/issues/298

**Comment by zwetan** [comment]
I gave a little skeleton of how one could implement it as a plugin for flow player
it's not that hard really (I personally just do not have the time to do it)

you can also look into the wiki documentation for details on specific things

**Comment by grantkemp** [comment]
I haven't done flash before - but I will have a go based on your skeleton as I think it will be useful.  Much appreciated @zwetan

**Comment by zwetan** [comment]
you're welcome
