### ISSUE TITLE
How to Track two parallel screens 

### ISSUE THREAD

**Issue by 22Round** [zwetan/as3-universal-analytics#26]
Hi, in my app I have two parallel screens, how can I track them the same tame?
tracker.screenview(screen1);
tracker.screenview(screen2);

in analytics Real-Time>Screens, they are rewriting each others.

**Comment by zwetan** [comment]
you need to provide a bit more info

which tracker are you using ?
how do you initialise the tracker ?
does it work with 1 screen ?

if so, when you call `tracker.screenview()`
what is the return value ?

also look the doc for Screens tracking
https://github.com/zwetan/as3-universal-analytics/wiki/TrackingDetailsAndTricks#screens

`tracker.screenview(screen1);`
not only `screen1` have to be a String
but you also have to define `APP_NAME`

eg. `tracker.set( Tracker.APP_NAME, "My App" );`

**Comment by 22Round** [comment]
this is my code:
`
public function sendPageview(page:String, title:String = "", event:String = ""):void {
    var trackingID:String = "XX-1234567-Y";
    var config:Configuration = new Configuration();
    config.forcePOST = true;
    var tracker:AppTracker = new AppTracker(trackingID, config);
    tracker.set(Tracker.APP_NAME, page);
    tracker.screenview(title);      
}
`
am I missing somthing?

**Comment by zwetan** [comment]
from

``` actionscript3
public function sendPageview(page:String, title:String = "", event:String = ""):void {
    var trackingID:String = "UA-76484529-3";
    var config:Configuration = new Configuration();
    config.forcePOST = true;
    var tracker:AppTracker = new AppTracker(trackingID, config);
    tracker.set(Tracker.APP_NAME, page);
    tracker.screenview(title);      
}
```

you need to make the `tracker` a unique instance
calling the tracker constructor on each function call will mess up your analytics state

also this
`tracker.set(Tracker.APP_NAME, page);`
will break your tracking

eg.

```
sendPageview( "/home", "Home Page" );
sendPageview( "/scores", "High Scores" );
```

means

```
tracker.set(Tracker.APP_NAME, "/home");
tracker.set(Tracker.APP_NAME, "/scores");
```

`APP_NAME` is also supposed to be unique and not change on each call
at best, google analytics will see 2 apps
at worst, google analytics could decide that the char `/` is not valid and ignore the request

The way you are merging pageview and screnview is a bit strange
they have both their own specific usages

it is perfectly OK to call pageview from an app, e.g. the page is "virtual" but it will work

from your main class do something like that

``` actionscript3

public var tracker: AppTracker;

public function initTracker():void
{
    var info:Dictionnary = new Dictionnary();
        info[ Tracker.APP_NAME ] = "My App Name";
        info[ Tracker.APP_ID ] = "com.something.appname";
        info[ Tracker.APP_VERSION ] = "1.0.0";

    var trackingID:String = "UA-76484529-3";
    var config:Configuration = new Configuration();
        config.forcePOST = true;

    tracker = new AppTracker( trackingID, config );
    tracker.add( info );
}

public function sendPageview( page:String, title:String = "", event:String = "" ):void
{
    if( !tracker )
    {
        initTracker(); // initialise the tracker if not found
    }

    if( title == "" )
    {
        title = page; // you could replace the '/' by ' ' (space) and convert to CamelCase for ex
    }

    tracker.screenview( title );
}
```

**Comment by 22Round** [comment]
@zwetan thanks for detailed replay, I will try.
